#!/usr/bin/env node

// Takes a list of queries and checks that:
// - Every query matches something in the repository
// - Every case in the repository matches exactly one query
// This is used to ensure that tracking

require('../src/common/tools/setup-ts-in-node.js');
require('../src/common/tools/checklist.ts');
